name: deploy

on:
  workflow_call:
    inputs:
      event_name:
        description: The original github.event_name object in the caller workflow
        required: true
        type: string
      installer_platforms:
        description: Comma-separated string of conda-style platforms for which it builds the installers.
        required: false
        type: string
        default: linux-64,win64,osx-arm64
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare-matrix:
    # See this SO answer for details on conditional matrices
    # https://stackoverflow.com/a/65434401/3407590
    name: Prepare matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Prepare matrix
        id: set-matrix
        shell: python
        # The Python versions chosen below will determine which
        # Python versions the installers will bundle. The general
        # principle is to follow the SPEC-0 recommendation:
        # https://scientific-python.org/specs/spec-0000/
        run: |
          import os
          import json
          elements = [
            {
              "os": "ubuntu-latest",
              "target-platform": "linux-64",
            },
            {
              "os": "macos-14",
              "target-platform": "osx-arm64",
            },
            {
              "os": "windows-latest",
              "target-platform": "win-64",
            },
          ]
          platforms_str = "${{ inputs.installer_platforms || 'linux-64,win-64,osx-arm64' }}"
          platforms = {p.strip() for p in platforms_str.split(",")}
          matrix = {"include": []}
          for element in elements:
            if element["target-platform"] in platforms:
              matrix["include"].append(element)
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"matrix={json.dumps(matrix)}\n")

  installers:
    name: Create ${{ matrix.target-platform }} installer
    runs-on: ${{ matrix.os }}
    needs: prepare-matrix
    if: startsWith(github.ref, 'refs/tags/') # Only run for tags
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare-matrix.outputs.matrix) }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: motile-tracker-installer

      - name: Install pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.43.2
          cache: false
          run-install: false
          manifest-path: motile-tracker-installer/pixi.toml

      - name: Install build tools (Windows only)
        if: runner.os == 'Windows'
        run: |
          $installer = "vs_BuildTools.exe"

          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_BuildTools.exe" -OutFile $installer

          Start-Process -Wait -FilePath .\$installer -ArgumentList `
            "--quiet", `
            "--wait", `
            "--norestart", `
            "--nocache", `
            "--add Microsoft.VisualStudio.Workload.VCTools", `
            "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64", `
            "--add Microsoft.VisualStudio.Component.Windows10SDK.19041", `
            "--includeRecommended"
        shell: pwsh

      - name: Install app dependencies
        working-directory: motile-tracker-installer
        run: pixi run setup

      - name: Build the PyPi package (Linux only)
        working-directory: motile-tracker-installer
        if: runner.os == 'Linux'
        run: pixi run build

      - name: Publish to PyPi (Linux only)
        uses: pypa/gh-action-pypi-publish@release/v1
        if: runner.os == 'Linux'
        with:
          packages-dir: motile-tracker-installer/dist
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Download installer app (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y makeself

      - name: Download installer app (macOS only)
        if: runner.os == 'macOS'
        run: |
          brew install create-dmg

      - name: Download installer app (Windows only)
        if: runner.os == 'Windows'
        run: |
          choco install -y innosetup

      - name: Package native app
        working-directory: motile-tracker-installer
        run: |
          pixi run create-installer
          mv dist/MotileTrackerInstaller.* MotileTrackerInstaller-${{ env.version }}-${{ runner.os }}-${{ env.arch-suffix }}.${{ env.extension }}

      - name: Get Release
        if: inputs.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        id: get_release
        uses: bruceadams/get-release@v1.3.2

      - name: Upload Release Asset
        if: inputs.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/motile-tracker-installer/dist/MotileTrackerInstaller.*
          asset_name: MotileTrackerInstaller-${{ env.version }}-${{ runner.os }}-${{ env.arch-suffix }}.${{ env.extension }}
          asset_content_type: application/octet-stream
